### ISSUE TITLE
Dodgeball

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#10]
**Minecraft username**: AwesomelyEpic1

**Applicable Realm – Skyblock or Minigames**: Minigames

**Your Idea**: A dodgeball minigame played just like regular dodgeball. you could play with either snowballs, firecharges (turn off their ability to destroy the surroundings), or a specially programmed object. (I suppose arrows could also be used). If you are hit you are out, last team standing wins, or if the game goes longer than a set amount of time the team with the most players still standing wins.

**Comment by joshwenke** [comment]
I like this idea. We will incorporate this!
