### ISSUE TITLE
Boat Race

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#12]
**Minecraft username**: AwesomelyEpic1

**Applicable Realm – Skyblock or Minigames**: Minigames

**Your Idea**: There is an ice track floating in the void that you have to navigate. along the way there are traps and shortcuts (shortcuts are hard to get onto and hard to navigate). If you fall off you either restart or there is a checkpoint system and you would go back to the previous checkpoint. Boats would have collisions on like Mario cart but punching would be disabled and there are no player controlled traps.

**Comment by joshwenke** [comment]
To be honest, games involving vehicles like boats or sheep will be difficult to make bug-free. I'm not sure we'll be able to incorporate this idea.
