### ISSUE TITLE
Defined building region

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#13]
**Minecraft username**: AwesomelyEpic1

**Applicable Realm – Skyblock or Minigames**: Skyblock

**Your Idea**: i played on skyblock quite a bit on the 1.8 server and I made an island that covered the entire area that i could build in. I remember it being annoying to do that though because I would do the crouch walk place thing one does when building in a straight line in the air. When I got to the end of the designated zone I was allowed to build in it would let me place one more block and then take it away and I'd fall to my death. I think there should be some way of telling where the edge of these boundaries are so that people who cant fly and have to build old school don't fall to their death when they reach the edge of the build zone. This marker could either be a ring of material or the edge of world boundary in a normal survival world (the stripped one that makes a square around the world).

**Comment by joshwenke** [comment]
You're going to love the new area definition system. You'll be able to expand your island building area and also see an outline of it.
