### ISSUE TITLE
Remove chat restrictions for doners

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#16]
**Your Minecraft Username**: AwesomelyEpic1

**Describe the Feature** - What do you envision for this feature if it was added to Cobalt? Doners don't have to leave the spawn area in order to run commands or chat.

**Does Everyone Want It?** - How important do you think this idea is to the community? I know that I want it and I also know that a lot of the other doners would like it.

**Affected Realms** - Will this idea affect the entire Cobalt Network or just one realm? Mainly the hub but really anywhere that has chat restrictions that aren't there for a really good reason.

**Affected Commands / Systems (optional)** - Which commands or systems would this feature integrate with?

**Additional Comments (optional)** Currently when you join the game the server wont let you chat. It says you must leave the spawn area to chat. I understand why its there as no body wants a spammer joining and posting a bunch of chat messages all at once. I do think that doners shouldnt have this restriction as they have, by donating to the server, shown that they like the server and wont spam the chat. This message happens whenever you are in the spawn area too, not when you first join, I think that the restriction should at least be taken away from again at least doners after that have left the spawn area once, if it is no removed entirely. (I was reading the wiki on the cobalt website and it says that doners can talk immediately so i'm making the feature request)

![ChatRestrictions](https://user-images.githubusercontent.com/31635960/57893288-36b57580-77f7-11e9-809f-32f8c1515224.PNG)

**Comment by TonyMaster21** [comment]
This has been fixed and is now live on the Cobalt server.
