### ISSUE TITLE
/repair cooldown is not working

### ISSUE THREAD

**Issue by liamlfc123** [CobaltMC/cobalt-issues#17]
**Specific Information**
- Your Minecraft username: liamlfc123
- Which realm were you on?: Survival
- Date and time the bug first occurred?: Sat 18 May, ~9:30am EST
- Which Minecraft version were you using?: 1.12.1

**Quality Filter**
- Did you test the bug again right before submitting the report?: Yes
- Have you looked through existing bug reports for similar ones to this?: Not extensively

**Trigger** - What command or action caused this bug to happen?
/gems cooldown buy repair

**Expected Result** - What did you think was going to happen?
The cooldown on my /repair to be removed

**Actual Result** - What actually happened?
Error message

**Exact Error Message** - Type all relevant messages word-for-word.
Invalid Cooldown. Use /cooldown for a list.

**Screenshots (optional)** - Very helpful in solving your bug quickly.

**Additional Comments (optional)**
I checked /cooldown and repair is listed as one of 4 I have, and the only one active. Using /gems cooldown will also tel me I have one active cooldown I can remove, only using the actual cooldown buy whatever command, I get the error.

**Comment by joshwenke** [comment]
Your command usage is invalid. For removing cooldowns from commands, make sure to include the slash. For example: /gems cooldown buy /repair instead of /gems cooldown buy repair.

I haven't tested it but it should be working fine since cooldown removals aren't specific to a certain thing.
