### ISSUE TITLE
regions dont display members correctly

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#2]
**Specific Information**
- Which realm were you on?: Survival
- Date and time the bug first occurred?: Happens on and off since the update to 1.12.2
- Coordinates (optional): you can check at /warp mine. the password is city

**Quality Filter**
- Did you test the bug again right before submitting the report?: yes
- Have you looked through existing bug reports for similar ones to this?: yes

**Trigger** - What command or action caused this bug to happen? /rg info

**Expected Result** - What did you think was going to happen? the list of members would show up in chat

**Actual Result** - What actually happened? it said <none> instead of listing the member names out

**Exact Error Message** - Type all relevant messages word-for-word. There is no error message

**Screenshots (optional)** - Very helpful in solving your bug quickly.

**Additional Comments (optional)**
Obviously this isnt a pressing concern as land protections do still work but if you have more than one player added to a region field ie. builder and owner it displays <none> instead of the names that belong in that category.

**Comment by joshwenke** [comment]
This bug has been fixed, and we increased data quality inspections for regions (making sure remnants of data isn't left in the region information blob)
Also ensured regions are properly protected
