### ISSUE TITLE
Pet falling bugs

### ISSUE THREAD

**Issue by KidOfCubes** [CobaltMC/cobalt-issues#21]
**Specific Information**
- Your Minecraft username: KidOfCubes
- Which realm were you on?: Creative
- Date and time the bug first occurred?: Saturday,may 25, 1:46 pm
- Which Minecraft version were you using?: 1.12.2
- Coordinates (optional):

**Quality Filter**
- Did you test the bug again right before submitting the report?: Yes
- Have you looked through existing bug reports for similar ones to this?: Yes

**Trigger** - When I let my pet take fall damage and die, he teleports back to where he fell from to show the dieing animation, and they take fall damage from falling onto slime blocks, and the fall damage isnt reduced when falling onto haybales.

**Expected Result** - Pet dies where he hit the ground, pet takes no damage when fall on slime, pet takes reduced damage when fall onto haybale.

**Actual Result** - Pet dies where he fell from and pet takes fall damage from slime, and hay bales dont reduce fall damage.

**Exact Error Message** No error message

**Screenshots (optional)** - Very helpful in solving your bug quickly. To fast, cant take.

**Additional Comments (optional)** None.

**Comment by joshwenke** [comment]
The pet should respawn shortly after dying with no penalties or issues right? If so, then this is just an annoyance and since the plugin is a third-party one, there's not much we can do to fix this.

In the long term I'd like to write my own pets plugin, but for now we're stuck with this one.
