### ISSUE TITLE
Plots separate when you do /plot clear

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#22]
**Specific Information**
- Your Minecraft username: AwesomelyEpic1
- Which realm were you on?: Creative
- Date and time the bug first occurred?: 5/30/19 (probably before this too though)
- Which Minecraft version were you using?: 1.12.2
- Coordinates (optional): XYZ: -1467/80/-967

**Quality Filter**
- Did you test the bug again right before submitting the report?: yes
- Have you looked through existing bug reports for similar ones to this?: yes

**Trigger** - What command or action caused this bug to happen? /plot clear

**Expected Result** - What did you think was going to happen? the plot would clear but stay combined.
![plots](https://user-images.githubusercontent.com/31635960/58681560-c4c64b80-8321-11e9-835d-24f167d74b88.png)

**Actual Result** - What actually happened? the plot cleared but did not stay together.

**Exact Error Message** - Type all relevant messages word-for-word.

**Screenshots (optional)** - Very helpful in solving your bug quickly.

**Additional Comments (optional)** I own eight plots next to each other and was building across them all but I wanted to pause that build so I made a schematic and then did /plot clear. when I did plot clear all eight plots become individual again.

**Comment by joshwenke** [comment]
With this third-party plugin, there's not much we can do to fix this. You can always re-merge right after clearing, and this helps us when we clear big plots of inactive players.

https://github.com/IntellectualSites/PlotSquared/issues/722
