### ISSUE TITLE
Cobalt bot not showing usernames.

### ISSUE THREAD

**Issue by KidOfCubes** [CobaltMC/cobalt-issues#23]
**Specific Information**
- Your Minecraft username: KidOfCubes
- Which realm were you on?: Discord
- Date and time the bug first occurred?: 2019/5/31 5:17
- Which Minecraft version were you using?: Not minecraft bug.
- Coordinates (optional):

**Quality Filter**
- Did you test the bug again right before submitting the report?: yee
- Have you looked through existing bug reports for similar ones to this?: yee

**Trigger** - !who

**Expected Result** - Would output how many players online and their usernames.

**Actual Result** - Only showed how many players online.

**Exact Error Message** - Online Players:
There are currently [some number] players online!

**Screenshots (optional)** - 
![image](https://user-images.githubusercontent.com/40485669/58698803-981c3d80-83ce-11e9-9259-36ca211a7ee7.png)

**Additional Comments (optional)** I want to see whos online now plz

**Comment by KidOfCubes** [comment]
Oh yes heres another problem
![image](https://user-images.githubusercontent.com/40485669/58738818-04805680-843a-11e9-8c96-5f5a8fe7e312.png)

**Comment by BradtheRad** [comment]
This is not a bug by the Cobalt bot. It is just showing 3 people on, but not listing their names on a server, because the server they are on is not shown by the bot.

**Comment by KidOfCubes** [comment]
Ok thx
