### ISSUE TITLE
Tphere bug

### ISSUE THREAD

**Issue by chris9740** [CobaltMC/cobalt-issues#25]
**Specific Information**
- Your Minecraft username: 3306
- Which realm were you on?: Survival
- Date and time the bug first occurred?: 16:20 ETC (~)
- Which Minecraft version were you using?: 1.12.2
- Coordinates (optional):

**Quality Filter**
- Did you test the bug again right before submitting the report?: Yes
- Have you looked through existing bug reports for similar ones to this?: Yes

**Trigger** - What command or action caused this bug to happen?
`/tphere <username>`

**Expected Result** - What did you think was going to happen?
You get a GUI with an "Accept" and "Deny" button

**Actual Result** - What actually happened?
You get an empty GUI

**Exact Error Message** - Type all relevant messages word-for-word.

**Screenshots (optional)** - Very helpful in solving your bug quickly.
![Screenshot from 2019-06-01 16-18-41](https://user-images.githubusercontent.com/33673505/58749688-42f13200-8489-11e9-94f9-c3d62b380858.png)

**Additional Comments (optional)**
When someone does `/tphere 3306` I get a GUI that's empty

**Comment by joshwenke** [comment]
It would be great if you could check and see if this was resolved. I believe we fixed it, but if you are still having the issue then there may be more things at play here.
