### ISSUE TITLE
/Slap doesn't work for players in other realms.

### ISSUE THREAD

**Issue by Vauxine** [CobaltMC/cobalt-issues#27]
**Specific Information**
- Your Minecraft username: Vauxine (However the bug only applies to those with the ability to /slap
- Which realm were you on?: Hub, however it doesn't matter
- Date and time the bug first occurred?: I'm unsure of the exact date but i saw it roughly 2 days ago.
- Which Minecraft version were you using?: 1.12.2
- Coordinates (optional):

**Quality Filter**
- Did you test the bug again right before submitting the report?: Yes
- Have you looked through existing bug reports for similar ones to this?: Yes

**Trigger** - What command or action caused this bug to happen? /slap (name) Is only triggered when the person being slapped is in a different realm to the one who runs the command

**Expected Result** - What did you think was going to happen? it would show their username and effect the player knockback

**Actual Result** - What actually happened? instead of providing a user it provided <none> and did not give the "victim" knockback

**Exact Error Message** - Type all relevant messages word-for-word. No error message

**Screenshots (optional)** - Very helpful in solving your bug quickly.
![image](https://user-images.githubusercontent.com/51339755/58830466-45e35280-8642-11e9-9f53-615c6db88e59.png)

**Additional Comments (optional)**

**Comment by joshwenke** [comment]
This is a small fix, and will be applied very soon.
