### ISSUE TITLE
Shop Signs

### ISSUE THREAD

**Issue by GoldenShiba** [CobaltMC/cobalt-issues#28]
**Specific Information**
- Your Minecraft username: GoldenShiba
- Which realm were you on?: Survival
- Date and time the bug first occurred?: 6/7/2019 11:18 EST (ish)
- Which Minecraft version were you using?: 1.12.2
- Coordinates (optional): 31235 22
 14512
**Quality Filter**
- Did you test the bug again right before submitting the report?: Yes
- Have you looked through existing bug reports for similar ones to this?: No

**Trigger** - What command or action caused this bug to happen?
Clicking on my shop sign at /warp shibaswood
**Expected Result** - What did you think was going to happen?
Buying wood from my shop and paying me
**Actual Result** - What actually happened?
Not buying anything and getting no money
**Exact Error Message** - Type all relevant messages word-for-word.
No error messages were given
**Screenshots (optional)** - Very helpful in solving your bug quickly.

**Additional Comments (optional)**
This bug did not happen to me but SweetyJane (and if im being honest i dont really trust her to submit an in depth bug report)

**Comment by joshwenke** [comment]
Chest shops are unfortunately disabled until we can re-do them. With the low volume of players and the increased manually-run shops, we've put this on low priority. The free chestshop plugin (the one that used to power those signs) just didn't cut it.
