### ISSUE TITLE
/sleep additional command mirroring sleeping in beds

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#3]
**Describe the Feature** - What do you envision for this feature if it was added to Cobalt? Upper doner ranks would have access to this command. It acts like a bed and has the same cool down but they dont actually have to go find a bed and click on it.

**Does Everyone Want It?** - How important do you think this idea is to the community? I know a few people like the idea, like liam and TripleButter but I dont think very many people relize how usefull it could be.

**Affected Realms** - Will this idea affect the entire Cobalt Network or just one realm? SkyBlock and Survival

**Affected Commands / Systems (optional)** - Which commands or systems would this feature integrate with? It would integrate with the ability to sleep in a bed.

**Additional Comments (optional)**

**Comment by joshwenke** [comment]
This feature has been added as a donor command for Elites+. It will be available tomorrow at 2am.
