### ISSUE TITLE
Survival showing offline when it's not

### ISSUE THREAD

**Issue by Treellane** [CobaltMC/cobalt-issues#30]
**Specific Information**
- Your Minecraft username: Ruslana
- Which realm were you on?: Hub
- Date and time the bug first occurred?: spotted 21/6/19, 10.40pm GMT
- Which Minecraft version were you using?: 1.12
- Coordinates (optional): Hub

**Quality Filter**
- Did you test the bug again right before submitting the report?: Yes
- Have you looked through existing bug reports for similar ones to this?: Yes

**Trigger** - What command or action caused this bug to happen? Selecting the Compass while in the Hub

**Expected Result** - What did you think was going to happen? View realms with the intention of selecting one.

**Actual Result** - What actually happened? Survival shows as offline, even when it is not

**Exact Error Message** - 'offline' showing for Survival when it's online.

**Screenshots (optional)** -![Screen Shot 2019-06-21 at 22 38 16](https://user-images.githubusercontent.com/6535735/59952926-e7a5d480-9475-11e9-8a96-cfca31e6c79b.png)
![Screen Shot 2019-06-21 at 22 38 22](https://user-images.githubusercontent.com/6535735/59952942-f7bdb400-9475-11e9-933b-76f104adfa1d.png)

**Additional Comments (optional)** first spotted by John McJohnson

**Comment by joshwenke** [comment]
We are in the process of completely rewriting our server status indicators and will have a better version added soon.
