### ISSUE TITLE
Wear items as hats

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#31]
**Your Minecraft Username**:
AwesomelyEpic1
**Describe the Feature** - What do you envision for this feature if it was added to Cobalt?
Certain doners can already wear any block as a hat, why not be able to wear items like iron ingots and clocks too?
**Does Everyone Want It?** - How important do you think this idea is to the community?
I have no idea. I just figured out it was a vanilla command so I am guessing there has to be a way to do it with a plugin
**Affected Realms** - Will this idea affect the entire Cobalt Network or just one realm?
all except the hub
**Affected Commands / Systems (optional)** - Which commands or systems would this feature integrate with?
/hat
**Additional Comments (optional)**

**Comment by joshwenke** [comment]
I wish this was possible, but unfortunately there's no way to do it.
