### ISSUE TITLE
Sell Granite/Andesite/Diorite

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#33]
**Your Minecraft Username**: AwesomelyEpic1

**Describe the Feature** - What do you envision for this feature if it was added to Cobalt? Add the three items in the name of this issue.

**Does Everyone Want It?** - How important do you think this idea is to the community? TripleButter and I do. I am sure others would like it as well.

**Affected Realms** - Will this idea affect the entire Cobalt Network or just one realm? Survival

**Affected Commands / Systems (optional)** - Which commands or systems would this feature integrate with? /sell and /buy

**Additional Comments (optional)**

**Comment by joshwenke** [comment]
Players can make shops to sell additional items.
