### ISSUE TITLE
Ability to silk touch, and de-regulate spawners.

### ISSUE THREAD

**Issue by liamlfc123** [CobaltMC/cobalt-issues#37]
**Your Minecraft Username**: liamlfc123

**Describe the Feature** - The ability to create mob farms for players to get better access to harder to get resources like gunpowder, bones, blaze rods, meats etc. Removing the restrictions on mob drops too will need to be done also, and the removal of all mob loots from the server shops buy and sell list.

**Does Everyone Want It?** - A mob spawner is one of the basic things any starting players base needs. Not everyone does it, not everyone wants it, but those that don't want it, don't /not/ want it. You know?

**Affected Realms** - Survival and I assume one day Skyblock

**Affected Commands / Systems (optional)** - None

**Additional Comments (optional)** - For this to work obviously mob loot would be needed to be removed from the /buy and /sell feature. Of course /buy would no longer be necessary, and /sell would mean people wouldn't get super rich from it. Let players sell it in their shops if they want, or create mob farms open to the public, or just have a private one in their base. It's a pretty common thing people want for their bases, but because the mob loots are included in the shop list, no one is allowed them.

**Comment by joshwenke** [comment]
Mob spawners can now be mined with silk touch pickaxes.
