### ISSUE TITLE
Unable to place Specific Block Type in Specific Location on Plot Creative

### ISSUE THREAD

**Issue by MisterTooh** [CobaltMC/cobalt-issues#39]
**Specific Information**
- Your Minecraft username: _MisterTooh_
- Which realm were you on?: _Creative_
- Date and time the bug first occurred?: _Sep/21/2019 22:00 I believe it existed since the beginning_
- Which Minecraft version were you using?: _1.14.4_ **_I've Since started using 1.12 but the Problem Persists_**
- Coordinates (optional): _Creative Plot 16;-3 Rawrznsocks_

**Quality Filter**
- Did you test the bug again right before submitting the report?: _Yes, multiple times._
- Have you looked through existing bug reports for similar ones to this?: _Yes_

**Trigger** - _Placing a single block Like Glazed Terracotta._

**Expected Result** - _Regular Block Placement_

**Actual Result** - _"You do not have permission for this."_

**Exact Error Message** - _"You do not have permission for this."_

**Screenshots (optional)** - _Very helpful in solving your bug quickly._

**Additional Comments (optional)** _I can place **normal blocks in a location, but not other types like Pink Glazed Terracotta.** Error message says; "You do not have permission for this.", however, just **next to the area I can place them fine.** Plot "16;-3 Rawrznsocks" in "Creative" I've place **Glowstone to indicate the area affected by the bug**._

**Comment by FosDoNuT** [comment]
when you're placing the terracotta make sure you aren't  right clicking the bedrock to place the coloured terracotta. I've tried this on my plot and it only says that message when I right click on the bedrock while trying to place the green glazed terracotta.
