### ISSUE TITLE
Stop mobs from ruining my crop fields

### ISSUE THREAD

**Issue by liamlfc123** [CobaltMC/cobalt-issues#42]
**Your Minecraft Username**: liamlfc123

**Describe the Feature** - When I have a field, I really hate it when I get random cows or pigs wandering through and turning the crop squares back into regular dirt.

**Does Everyone Want It?** - Yes, I emailed everyone, and everyone replied saying yes.

**Affected Realms** - Survival

**Affected Commands / Systems (optional)** - None

**Additional Comments (optional)** Please

**Comment by joshwenke** [comment]
Just add a fence. Would  take too many  resources  to track mob movements in addition to player.
