### ISSUE TITLE
clan chat toggle

### ISSUE THREAD

**Issue by SubjectI7731** [CobaltMC/cobalt-issues#44]
I7731

**Describe the Feature** -  Im using the "/clan chat toggle" command quite frequently as of lately and i find it annoying to type the whole thing every time. Id suggest shortening it to something like /cct.

**Does Everyone Want It?** - I don't know if other people want it but I think this could be an improvement to the command that is currently active.

**Affected Realms** - This will probably not affect anything at all.

**Affected Commands / Systems (optional)** - The "/clan chat toggle" command will probably get replaced or the command will be implemented while keeping the old one.

**Comment by FosDoNuT** [comment]
Pretty sure theres already a /cct command that toggles the clan chat.

**Comment by AwesomelyEpic1** [comment]
There is a /cct command that has been made. (ik this is exactly what Fos said. I'm testing something out in the process of writing this comment.)
