### ISSUE TITLE
Cobblestone duplication???

### ISSUE THREAD

**Issue by RedstoneGate2010** [CobaltMC/cobalt-issues#48]
When i mine cobble, sometimes it duplicates and gives me 2. help???
RedstonGate2010
survival
8:31AM 2019 10 30
1.12.2 OptiFine

yes
yes

breaking stone with a pickaxe(any)
get 1 cobblestone

i got 2

there was no error message

**Comment by joshwenke** [comment]
Could this be due to an active McMMO skill? Or does the item have any enchantments on it?

- Josh

**Comment by FosDoNuT** [comment]
Yeah its an MMO thing, depend son what mining level you are, it has a xhance of giving you more cobble than a single.
