### ISSUE TITLE
Discord bot only connected to hub

### ISSUE THREAD

**Issue by KidOfCubes** [CobaltMC/cobalt-issues#55]
**Specific Information**
- Your Minecraft username: KidOfCubes
- Which realm were you on?: Discord
- Date and time the bug first occurred?: Saturday, May 30th, 2020 6:44 AM, gmt+8, mightve begun sooner
- Which Minecraft version were you using?: discord
- Coordinates (optional):

**Quality Filter**
- Did you test the bug again right before submitting the report?: 
- Have you looked through existing bug reports for similar ones to this?: yea

**Trigger** - What command or action caused this bug to happen? talking in realms which arent hub, moving into realms that arent hub in cobalt

**Expected Result** - the bot would show chat and joins/leaves outside of the hub

**Actual Result** - it didnt

**Exact Error Message** - no error msg

**Screenshots (optional)** - 
![test1](https://user-images.githubusercontent.com/40485669/83331796-c88d0500-a2ca-11ea-889d-ef0f11e76584.png)
![test2](https://user-images.githubusercontent.com/40485669/83331808-cf1b7c80-a2ca-11ea-911b-da4bd56d1208.PNG)

The user Clariissa is shown joining hub, and nothing else, but from the !who command, Clariissa is shown in survival.

**Additional Comments (optional)** i think the cobalt bot disconnected from the other realms somehow? also i think it could be fixed by a restart, but i thought id post this report here just in case

**Comment by HelloImJake** [comment]
Bug fixed in game, thankyou for bringing it up.
