### ISSUE TITLE
GUI API rewrite and toggle specific GUIs on or off

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#6]
**Your Minecraft Username**: AwesomelyEpic1

**Describe the Feature** - What do you envision for this feature if it was added to Cobalt? Players can enable/disable popups for specific features.

**Does Everyone Want It?** - How important do you think this idea is to the community? I dont know if anyone but me has thought of this before.

**Affected Realms** - Will this idea affect the entire Cobalt Network or just one realm? All realms with any popups.

**Affected Commands / Systems (optional)** - Which commands or systems would this feature integrate with? /set popup

**Additional Comments (optional)**
Currently when you disable or enable popup settings it affects all popup menus. I think it would be cool if you could enable or disable popups for certain features, like /set popup shop or /set popup tpa, etc. There would be a setting for all the different popup menus that exist as well as a master control like there is now.

**Comment by joshwenke** [comment]
Sounds like a great idea. We will do it!

@CobaltMC/developers

**Comment by joshwenke** [comment]
Popups have been unstable for awhile on Minecraft (minor updates to lots of things can break certain popups) so we will need to rewrite the popup API with our own code. Estimated time to complete this ticket, including the recoded API, is 1-2 weeks.
