### ISSUE TITLE
Bedwars+Mega walls

### ISSUE THREAD

**Issue by KidOfCubes** [CobaltMC/cobalt-issues#8]
**KidOfCubes**:

**Minigames**:

**also add a game where first, theres a 50*50 size plot for everyone, everyone gets 2 stacks of cobble, 1 stack of planks,  2 lava buckets , 15 diamonds. Everyone has some kinda respawn thingy at the far corner of their base, like a peice of obsidian which lets them respawn, there are ores underground, and when done building everyone fight
the map for the game is 300*300
the plots for everyone are on the corners
after 5 minutes  if noone win(by destroying all other respawning thingys and then killing everyone)
the next person who gets a kill wins, and all respawning thingys dissapear, so if you die from natural cause u cant play again
oh also maybe add some special kit things**:

**Comment by joshwenke** [comment]
We will definitely have an objective-based PvP battle game mode for the future Minigames server.
