### ISSUE TITLE
Central resource island

### ISSUE THREAD

**Issue by AwesomelyEpic1** [CobaltMC/cobalt-issues#9]
**Minecraft username**: AwesomelyEpic1

**Applicable Realm – Skyblock or Minigames**: Skyblock

**Your Idea**: Add a "mother ship" or central island to the skyblock realm that has ores and valuable resources in it. Players can /warp to the island and collect these resources, it would be first come first serve for the resources and once they are gone they are gone. The island would reset either every day or every time all the resources are mined up (once a day would keep more balance in the game and probably be easier to program. This would provide a fun safe place to mine resources and would be great for new players who don't have the money to buy diamonds.
The island could also have things like dirt or lava to help players progress farther into the game.

**Comment by joshwenke** [comment]
We will definitely have some kind of resource generation area. How can we give players items without them getting tons of things, @AwesomelyEpic1? In the past we had block breaks limited by a donor rank.

**Comment by AwesomelyEpic1** [comment]
You could have some system where they are limited to a certain number of materials per day. Stone obviously doesn't really matter as people will have a cobble stone generator on their home islands so they should be able to get as much of that as they want (obviously the market value would be lower) and then they are limited to like 10 diamonds a day, 20 iron ore a day, 20 gold ore a day, etc. obviously that is just an example but a system like that would keep players from getting a lot of valuable resources all at once.

**Comment by AwesomelyEpic1** [comment]
Josh I have a video file of a item generator that I saw on another server that i just "rediscovered" on my pc. I cant attach it here but I can dm it to you if you want. basically its a cobblestone spawner in spawn that spawns anything from cobble stone to diamond ore.
